apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: sgrvvgyre-python 
  janus-idp.io/tekton: sgrvvgyre-python
  backstage.io/kubernetes-id: sgrvvgyre-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sgrvvgyre-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  